export const INIT_HOME_DATA_ACTION = 'INIT_HOME_DATA_ACTION';
export const CHANGE_TOP_BUTTON_VISIBILITY = 'CHANGE_TOP_BUTTON_VISIBILITY';
export const LOAD_MORE_DATA = 'LOAD_MORE_DATA';
export const LOAD_AUTHOR_DATA = 'LOAD_AUTHOR_DATA';