export const SEARCH_BAR_FOCUSED = 'SEARCH_BAR_FOCUSED';
export const SEARCH_BAR_BLUR = 'SEARCH_BAR_BLUR';
export const GET_HOT_TOPICS = 'GET_HOT_TOPICS';
export const HOT_TOPIC_MOUSE_IN = 'HOT_TOPIC_MOUSE_IN';
export const HOT_TOPIC_MOUSE_OUT = 'HOT_TOPIC_MOUSE_OUT';
export const SWITCH_PAGE = 'SWITCH_PAGE';

export const TOPICS_PER_PAGE = 10;