export const LOAD_USER_PROFILE = 'LOAD_USER_PROFILE';
export const LOAD_USER_TIMELINE = 'LOAD_USER_TIMELINE';
export const LOAD_FOLLOWING = 'LOAD_FOLLOWING';
export const LOAD_FOLLOWER = 'LOAD_FOLLOWER';